#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ] || [ "$branch" = "development" ]; then
  echo "You can't commit directly to $branch branch"
  exit 1
fi

yarn test
echo "All Good, you can commit"
